name: QA

on:
  push:
    branches:
      - master
      - development
      - "v1.x-*"
      - "feature/*"
      - "issue/*"
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install tools via PHIVE
        run: make install-tools

      - name: Check for PHP parse errors
        run: make phplint

      - name: Composer install
        run: make composer-install-dev

      - name: Run PHPStan
        run: make phpstan

      - name: Run PHPUnit
        run: make phpunit

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: clover-report
          path: tests/clover.xml

  release:
    runs-on: ubuntu-latest
    needs:
      - run-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract version
        id: data
        run: |
          # Strip git ref prefix from version
          RELEASE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && RELEASE_VERSION=$(echo $RELEASE_VERSION | sed -e 's/^v//')

          echo $RELEASE_VERSION
          echo "##[set-output name=version;]$RELEASE_VERSION"

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Version ${{ steps.data.outputs.version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}